# Default values for tor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cowrie/cowrie
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


service:
  main:
    type: LoadBalancer
    ports:
      http:
        enabled: true
        port: 2222
      telnet:
        enabled: true
        port: 2223

persistence:
  config:
    enabled: true
    mountPath: /cowrie/cowrie-git/var
    accessMode: ReadWriteMany
    size: 5Gi

env:
  - name: COWRIE_TELNET_ENABLED
    value: "True"

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
