# Default values for navidrome.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/parrotsec/project/parrot-mirror-docker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "main"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


service:
  main:
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 80
      rsync:
        enabled: true
        port: 873


ingress:
  # -- Enable and configure ingress for navidrome
  main:
    enabled: false
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              port: http

persistence:
  config:
    enabled: true
    mountPath: /mirror
    accessMode: ReadWriteMany
    size: 600Gi

env:
  SOURCE: "rsync://rsync.parrot.sh:/parrot" # Where the mirror should sync from
  BWLIMIT: "0" # Bandwidth limit for rsync


resources:
  limits:
    cpu: 1000m
    memory: 8096Mi # Can use alot of memory due to file caching
  requests:
    cpu: 500m
    memory: 1024Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
