# Default values for navidrome.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: deluan/navidrome
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.50.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


service:
  main:
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 4533


ingress:
  # -- Enable and configure ingress for navidrome
  main:
    enabled: false
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              port: 80

persistence:
  config:
    enabled: true
    mountPath: /data
    accessMode: ReadWriteMany
    size: 2Gi
  music:
    enabled: true
    mountPath: /music
    accessMode: ReadWriteMany
    size: 5Gi
    # If you wish to use a hostpath, update comment out the access mode/size, and uncomment the following
    # type: hostPath
    # hostPath: /path/to/your/music
    # If you have an existing PVC with your music:
    # type: pvc
    # existingClaim: myMusicClaim

env:
  ND_SCANSCHEDULE: 1h
  ND_LOGLEVEL: info
  ND_SESSIONTIMEOUT: 24h
  ND_BASEURL: ""

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
